### ISSUE TITLE
Why is the parameter amq_broker_enable needed to enable Prometheus plugin

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#63]
##### SUMMARY
I would expect that the setting `activemq_prometheus_enabled`.  True would be enough to include the Prometheus metrics plugin. However this did not work and this step of the playbook was skipped. I needed to enable the setting` amq_broker_enable: True`. I find the setting amq_broker_anable a bit unclear and whats the reason that it is needed for the Prometheus plugin? 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Hello Robert; that is because the downstream product Red Hat AMQ Broker already contains the plugin, and the variable control whether to enable it (not the prefix `amq_broker_` and not `activemq_`. For upstream, I have the implementation with the additional download in the backlog, but not actively worked on yet.

**Comment by RobertFloor** [comment]
Thanks :)
